name: Validate Flyway Migrations

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  validate-migrations:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:17-alpine
        env:
          POSTGRES_DB: mydatabase
          POSTGRES_USER: myuser
          POSTGRES_PASSWORD: secret
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Wait for Postgres to be ready
        run: |
          for i in {1..15}; do
            pg_isready -h localhost -p 5432 -U myuser && exit 0
            echo "Waiting for Postgres to start..."
            sleep 3
          done
          echo "Postgres did not respond in time" && exit 1
        env:
          PGPASSWORD: secret

      - name: Run Flyway migrations
        run: |
          mvn flyway:migrate \
            -Dflyway.url=jdbc:postgresql://localhost:5432/mydatabase \
            -Dflyway.user=myuser \
            -Dflyway.password=secret

      - name: Validate Flyway migrations
        run: |
          mvn flyway:validate \
            -Dflyway.url=jdbc:postgresql://localhost:5432/mydatabase \
            -Dflyway.user=myuser \
            -Dflyway.password=secret

      - name: Generate migration report
        if: always()
        run: |
          mvn flyway:info \
            -Dflyway.url=jdbc:postgresql://localhost:5432/mydatabase \
            -Dflyway.user=myuser \
            -Dflyway.password=secret
